"""Known apps and websites, including Turkish government, education, and daily services."""

from __future__ import annotations

from typing import Any

# Canonical name -> local app(s) and/or website.
# Apps are tried first; URL is used when no app launches (or for sites).
KNOWN_TARGETS: dict[str, dict[str, Any]] = {
    # ── International apps & sites ──
    "youtube": {"url": "https://www.youtube.com"},
    "google": {"url": "https://www.google.com.tr"},
    "gmail": {"url": "https://mail.google.com"},
    "discord": {"apps": ["discord"], "url": "https://discord.com/app"},
    "spotify": {"apps": ["spotify"], "url": "https://open.spotify.com"},
    "netflix": {"url": "https://www.netflix.com"},
    "github": {"url": "https://github.com"},
    "slack": {"apps": ["slack"], "url": "https://slack.com"},
    "reddit": {"url": "https://www.reddit.com"},
    "twitter": {"url": "https://x.com"},
    "facebook": {"url": "https://www.facebook.com"},
    "instagram": {"url": "https://www.instagram.com"},
    "tiktok": {"url": "https://www.tiktok.com"},
    "twitch": {"url": "https://www.twitch.tv"},
    "amazon": {"url": "https://www.amazon.com.tr"},
    "wikipedia": {"url": "https://tr.wikipedia.org"},
    "linkedin": {"url": "https://www.linkedin.com"},
    "whatsapp": {"apps": ["whatsapp"], "url": "https://web.whatsapp.com"},
    "telegram": {"apps": ["telegram"], "url": "https://web.telegram.org"},
    "chatgpt": {"url": "https://chatgpt.com"},
    "maps": {"url": "https://maps.google.com"},
    "drive": {"url": "https://drive.google.com"},
    "outlook": {"url": "https://outlook.live.com"},
    "teams": {"apps": ["ms-teams", "teams"], "url": "https://teams.microsoft.com"},
    "zoom": {"apps": ["zoom"], "url": "https://zoom.us"},
    "primevideo": {"url": "https://www.primevideo.com"},
    "disneyplus": {"url": "https://www.disneyplus.com"},
    "stackoverflow": {"url": "https://stackoverflow.com"},
    "udemy": {"url": "https://www.udemy.com"},
    "coursera": {"url": "https://www.coursera.org"},
    "khanacademy": {"url": "https://tr.khanacademy.org"},
    "duolingo": {"url": "https://www.duolingo.com"},
    # ── Desktop apps ──
    "notepad": {"apps": ["notepad"]},
    "calculator": {"apps": ["calc"]},
    "paint": {"apps": ["mspaint"]},
    "explorer": {"apps": ["explorer"]},
    "settings": {"apps": ["ms-settings:"]},
    "cmd": {"apps": ["cmd"]},
    "powershell": {"apps": ["powershell"]},
    "taskmgr": {"apps": ["taskmgr"]},
    "vscode": {"apps": ["code"]},
    "cursor": {"apps": ["cursor"]},
    "chrome": {"apps": ["chrome"]},
    "edge": {"apps": ["msedge"]},
    "firefox": {"apps": ["firefox"]},
    "steam": {"apps": ["steam"]},
    "word": {"apps": ["winword"]},
    "excel": {"apps": ["excel"]},
    "powerpoint": {"apps": ["powerpnt"]},
    # ── Turkish news & portals ──
    "hurriyet": {"url": "https://www.hurriyet.com.tr"},
    "milliyet": {"url": "https://www.milliyet.com.tr"},
    "sabah": {"url": "https://www.sabah.com.tr"},
    "sozcu": {"url": "https://www.sozcu.com.tr"},
    "haberturk": {"url": "https://www.haberturk.com"},
    "ntv": {"url": "https://www.ntv.com.tr"},
    "cnnturk": {"url": "https://www.cnnturk.com"},
    "trthaber": {"url": "https://www.trthaber.com"},
    "bbcturkce": {"url": "https://www.bbc.com/turkce"},
    "anadoluajansi": {"url": "https://www.aa.com.tr"},
    "yenisafak": {"url": "https://www.yenisafak.com"},
    "cumhuriyet": {"url": "https://www.cumhuriyet.com.tr"},
    "t24": {"url": "https://t24.com.tr"},
    "onedio": {"url": "https://onedio.com"},
    "mynet": {"url": "https://www.mynet.com"},
    "haberler": {"url": "https://www.haberler.com"},
    "ensonhaber": {"url": "https://www.ensonhaber.com"},
    # ── Turkish shopping ──
    "trendyol": {"url": "https://www.trendyol.com"},
    "hepsiburada": {"url": "https://www.hepsiburada.com"},
    "n11": {"url": "https://www.n11.com"},
    "sahibinden": {"url": "https://www.sahibinden.com"},
    "cimri": {"url": "https://www.cimri.com"},
    "akakce": {"url": "https://www.akakce.com"},
    "pttavm": {"url": "https://www.pttavm.com"},
    "lcwaikiki": {"url": "https://www.lcwaikiki.com"},
    "defacto": {"url": "https://www.defacto.com.tr"},
    "migros": {"url": "https://www.migros.com.tr"},
    # ── Food & delivery ──
    "yemeksepeti": {"url": "https://www.yemeksepeti.com"},
    "getir": {"url": "https://getir.com"},
    "trendyolyemek": {"url": "https://www.trendyol.com/yemek"},
    # ── Travel ──
    "obilet": {"url": "https://www.obilet.com"},
    "enuygun": {"url": "https://www.enuygun.com"},
    "thy": {"url": "https://www.turkishairlines.com"},
    "pegasus": {"url": "https://www.flypgs.com"},
    "tcdd": {"url": "https://ebilet.tcddtasimacilik.gov.tr"},
    # ── Banks & payments ──
    "isbank": {"url": "https://www.isbank.com.tr"},
    "garanti": {"url": "https://www.garantibbva.com.tr"},
    "yapikredi": {"url": "https://www.yapikredi.com.tr"},
    "akbank": {"url": "https://www.akbank.com"},
    "ziraat": {"url": "https://www.ziraatbank.com.tr"},
    "halkbank": {"url": "https://www.halkbank.com.tr"},
    "vakifbank": {"url": "https://www.vakifbank.com.tr"},
    "papara": {"url": "https://www.papara.com"},
    # ── Turkish TV / streaming ──
    "blutv": {"url": "https://www.blutv.com"},
    "exxen": {"url": "https://www.exxen.com"},
    "gain": {"url": "https://gain.tv"},
    "tabii": {"url": "https://www.tabii.com"},
    "puhutv": {"url": "https://puhutv.com"},
    "trt": {"url": "https://www.trt.net.tr"},
    "showtv": {"url": "https://www.showtv.com.tr"},
    "startv": {"url": "https://www.startv.com.tr"},
    "kanald": {"url": "https://www.kanald.com.tr"},
    "atv": {"url": "https://www.atv.com.tr"},
    "nowtv": {"url": "https://www.nowtv.com.tr"},
    "tv8": {"url": "https://www.tv8.com.tr"},
    # ── Sports ──
    "tff": {"url": "https://www.tff.org"},
    "mackolik": {"url": "https://www.mackolik.com"},
    "ntvspor": {"url": "https://www.ntvspor.net"},
    "fenerbahce": {"url": "https://www.fenerbahce.org"},
    "galatasaray": {"url": "https://www.galatasaray.org"},
    "besiktas": {"url": "https://www.besiktas.com.tr"},
    "trabzonspor": {"url": "https://www.trabzonspor.org.tr"},
    # ── Government ──
    "edevlet": {"url": "https://www.turkiye.gov.tr"},
    "meb": {"url": "https://www.meb.gov.tr"},
    "eokul": {"url": "https://e-okul.meb.gov.tr"},
    "eba": {"url": "https://www.eba.gov.tr"},
    "mebbis": {"url": "https://mebbis.meb.gov.tr"},
    "ogmmateryal": {"url": "https://ogmmateryal.eba.gov.tr"},
    "odsgm": {"url": "https://odsgm.meb.gov.tr"},
    "yok": {"url": "https://www.yok.gov.tr"},
    "yokatlas": {"url": "https://yokatlas.yok.gov.tr"},
    "osym": {"url": "https://www.osym.gov.tr"},
    "saglik": {"url": "https://www.saglik.gov.tr"},
    "enabiz": {"url": "https://enabiz.gov.tr"},
    "mhrs": {"url": "https://www.mhrs.gov.tr"},
    "sgk": {"url": "https://www.sgk.gov.tr"},
    "nvi": {"url": "https://www.nvi.gov.tr"},
    "gib": {"url": "https://www.gib.gov.tr"},
    "uyap": {"url": "https://vatandas.uyap.gov.tr"},
    "emniyet": {"url": "https://www.egm.gov.tr"},
    "jandarma": {"url": "https://www.jandarma.gov.tr"},
    "icisleri": {"url": "https://www.icisleri.gov.tr"},
    "disisleri": {"url": "https://www.mfa.gov.tr"},
    "adalet": {"url": "https://www.adalet.gov.tr"},
    "tbmm": {"url": "https://www.tbmm.gov.tr"},
    "cumhurbaskanligi": {"url": "https://www.tccb.gov.tr"},
    "resmigazete": {"url": "https://www.resmigazete.gov.tr"},
    "afad": {"url": "https://www.afad.gov.tr"},
    "mgm": {"url": "https://www.mgm.gov.tr"},
    "ptt": {"url": "https://www.ptt.gov.tr"},
    "iskur": {"url": "https://www.iskur.gov.tr"},
    "kosgeb": {"url": "https://www.kosgeb.gov.tr"},
    "diyanet": {"url": "https://www.diyanet.gov.tr"},
    "tuik": {"url": "https://www.tuik.gov.tr"},
    "hmb": {"url": "https://www.hmb.gov.tr"},
    "ktb": {"url": "https://www.ktb.gov.tr"},
    "tarim": {"url": "https://www.tarimorman.gov.tr"},
    "uab": {"url": "https://www.uab.gov.tr"},
    "tubitak": {"url": "https://www.tubitak.gov.tr"},
    # ── Universities ──
    "odtu": {"url": "https://www.metu.edu.tr"},
    "itu": {"url": "https://www.itu.edu.tr"},
    "bogazici": {"url": "https://www.bogazici.edu.tr"},
    "hacettepe": {"url": "https://www.hacettepe.edu.tr"},
    "ankarauni": {"url": "https://www.ankara.edu.tr"},
    "istanbuluni": {"url": "https://www.istanbul.edu.tr"},
    "gaziuni": {"url": "https://gazi.edu.tr"},
    "ege": {"url": "https://www.ege.edu.tr"},
    "yildiz": {"url": "https://www.yildiz.edu.tr"},
    "marmara": {"url": "https://www.marmara.edu.tr"},
    "bilkent": {"url": "https://w3.bilkent.edu.tr"},
    "kocuni": {"url": "https://www.ku.edu.tr"},
    "sabanci": {"url": "https://www.sabanciuniv.edu"},
    "anadoluuni": {"url": "https://www.anadolu.edu.tr"},
    "aof": {"url": "https://www.anadolu.edu.tr/acikogretim"},
    "deu": {"url": "https://www.deu.edu.tr"},
    "ktu": {"url": "https://www.ktu.edu.tr"},
    "bau": {"url": "https://bau.edu.tr"},
    "yeditepe": {"url": "https://yeditepe.edu.tr"},
    "tobb": {"url": "https://www.etu.edu.tr"},
    "ozyegin": {"url": "https://www.ozyegin.edu.tr"},
    "akdeniz": {"url": "https://www.akdeniz.edu.tr"},
    "cukurova": {"url": "https://www.cu.edu.tr"},
    "uludag": {"url": "https://www.uludag.edu.tr"},
    "selcuk": {"url": "https://www.selcuk.edu.tr"},
    "sakarya": {"url": "https://www.sakarya.edu.tr"},
    "kocaeli": {"url": "https://www.kocaeli.edu.tr"},
    "ataturkuni": {"url": "https://www.atauni.edu.tr"},
    "omu": {"url": "https://www.omu.edu.tr"},
    "iuc": {"url": "https://www.iuc.edu.tr"},
}

# Spoken / informal names (EN + TR, including common STT spellings) -> canonical key
ALIASES: dict[str, str] = {
    # International
    "yt": "youtube",
    "you tube": "youtube",
    "you toob": "youtube",
    "you tup": "youtube",
    "yutub": "youtube",
    "yutup": "youtube",
    "youtub": "youtube",
    "yutube": "youtube",
    "yu tub": "youtube",
    "you tüp": "youtube",
    "google chrome": "chrome",
    "microsoft edge": "edge",
    "vs code": "vscode",
    "visual studio code": "vscode",
    "code": "vscode",
    "calc": "calculator",
    "hesap makinesi": "calculator",
    "file explorer": "explorer",
    "dosya gezgini": "explorer",
    "this pc": "explorer",
    "windows settings": "settings",
    "ayarlar": "settings",
    "task manager": "taskmgr",
    "gorev yoneticisi": "taskmgr",
    "command prompt": "cmd",
    "terminal": "powershell",
    "x": "twitter",
    "x twitter": "twitter",
    "whats app": "whatsapp",
    "whatsapp web": "whatsapp",
    "chat gpt": "chatgpt",
    "chat g p t": "chatgpt",
    "yapay zeka": "chatgpt",
    "google maps": "maps",
    "harita": "maps",
    "haritalar": "maps",
    "google drive": "drive",
    "prime video": "primevideo",
    "disney plus": "disneyplus",
    "disney": "disneyplus",
    "stack overflow": "stackoverflow",
    "microsoft word": "word",
    "microsoft excel": "excel",
    "microsoft powerpoint": "powerpoint",
    "power point": "powerpoint",
    "ms teams": "teams",
    "microsoft teams": "teams",
    "mail": "gmail",
    "email": "gmail",
    "e posta": "gmail",
    "eposta": "gmail",
    "not defteri": "notepad",
    "diskord": "discord",
    "diskort": "discord",
    "discort": "discord",
    "netfilix": "netflix",
    "insta": "instagram",
    "face": "facebook",
    "vikipedi": "wikipedia",
    "viki": "wikipedia",
    "khan academy": "khanacademy",
    "han akademi": "khanacademy",
    # News
    "hurriyet": "hurriyet",
    "hürriyet": "hurriyet",
    "sözcü": "sozcu",
    "sozcu gazete": "sozcu",
    "haber turk": "haberturk",
    "cnn turk": "cnnturk",
    "cnn türk": "cnnturk",
    "trt haber": "trthaber",
    "bbc turkce": "bbcturkce",
    "bbc türkçe": "bbcturkce",
    "anadolu ajansi": "anadoluajansi",
    "anadolu ajansı": "anadoluajansi",
    "aa": "anadoluajansi",
    "yeni safak": "yenisafak",
    "yeni şafak": "yenisafak",
    "en son haber": "ensonhaber",
    # Shopping
    "trendyol": "trendyol",
    "trend yol": "trendyol",
    "hepsi burada": "hepsiburada",
    "hepsiburada": "hepsiburada",
    "n on bir": "n11",
    "n11": "n11",
    "sahibinden": "sahibinden",
    "sahibin den": "sahibinden",
    "cimri": "cimri",
    "akakçe": "akakce",
    "akakce": "akakce",
    "ptt avm": "pttavm",
    "lc waikiki": "lcwaikiki",
    "lcw": "lcwaikiki",
    # Food
    "yemek sepeti": "yemeksepeti",
    "yemeksepeti": "yemeksepeti",
    "trendyol yemek": "trendyolyemek",
    # Travel
    "o bilet": "obilet",
    "en uygun": "enuygun",
    "turkish airlines": "thy",
    "turk hava yollari": "thy",
    "türk hava yolları": "thy",
    "thy": "thy",
    "pegasus": "pegasus",
    "tren": "tcdd",
    "tcdd": "tcdd",
    "e bilet": "tcdd",
    # Banks
    "is bankasi": "isbank",
    "iş bankası": "isbank",
    "isbank": "isbank",
    "garanti bbva": "garanti",
    "garanti": "garanti",
    "yapi kredi": "yapikredi",
    "yapı kredi": "yapikredi",
    "akbank": "akbank",
    "ziraat bankasi": "ziraat",
    "ziraat bankası": "ziraat",
    "halk bankasi": "halkbank",
    "halkbank": "halkbank",
    "vakif bank": "vakifbank",
    "vakıfbank": "vakifbank",
    # TV
    "blu tv": "blutv",
    "blue tv": "blutv",
    "show tv": "showtv",
    "star tv": "startv",
    "kanal d": "kanald",
    "now tv": "nowtv",
    "fox": "nowtv",
    "tv 8": "tv8",
    "puhu tv": "puhutv",
    # Sports
    "mac kolik": "mackolik",
    "maçkolik": "mackolik",
    "ntv spor": "ntvspor",
    "fener": "fenerbahce",
    "fenerbahçe": "fenerbahce",
    "gs": "galatasaray",
    "cimbom": "galatasaray",
    "beşiktaş": "besiktas",
    "besiktas": "besiktas",
    "bjk": "besiktas",
    "trabzon": "trabzonspor",
    # Government / education
    "e devlet": "edevlet",
    "edevlet": "edevlet",
    "e-devlet": "edevlet",
    "turkiye gov": "edevlet",
    "türkiye": "edevlet",
    "devlet": "edevlet",
    "milli egitim": "meb",
    "milli eğitim": "meb",
    "milli egitim bakanligi": "meb",
    "e okul": "eokul",
    "e-okul": "eokul",
    "eokul": "eokul",
    "okul": "eokul",
    "eba": "eba",
    "e b a": "eba",
    "egitim bilisim agi": "eba",
    "eğitim bilişim ağı": "eba",
    "meb bis": "mebbis",
    "ogm materyal": "ogmmateryal",
    "materyal": "ogmmateryal",
    "yok": "yok",
    "yök": "yok",
    "yuksekogretim": "yok",
    "yükseköğretim": "yok",
    "yok atlas": "yokatlas",
    "osym": "osym",
    "ösym": "osym",
    "ogrenci secme": "osym",
    "yks": "osym",
    "lgs": "odsgm",
    "saglik bakanligi": "saglik",
    "sağlık bakanlığı": "saglik",
    "e nabiz": "enabiz",
    "e nabız": "enabiz",
    "enabiz": "enabiz",
    "mhrs": "mhrs",
    "hastane randevu": "mhrs",
    "randevu": "mhrs",
    "sgk": "sgk",
    "sosyal guvenlik": "sgk",
    "nufus mudurlugu": "nvi",
    "nüfus": "nvi",
    "nvi": "nvi",
    "gelir idaresi": "gib",
    "vergi dairesi": "gib",
    "gib": "gib",
    "uyap": "uyap",
    "emniyet": "emniyet",
    "polis": "emniyet",
    "jandarma": "jandarma",
    "icisleri": "icisleri",
    "içişleri": "icisleri",
    "disisleri": "disisleri",
    "dışişleri": "disisleri",
    "meclis": "tbmm",
    "tbmm": "tbmm",
    "cumhurbaskanligi": "cumhurbaskanligi",
    "cumhurbaşkanlığı": "cumhurbaskanligi",
    "resmi gazete": "resmigazete",
    "afad": "afad",
    "hava durumu": "mgm",
    "meteoroloji": "mgm",
    "ptt": "ptt",
    "posta": "ptt",
    "iskur": "iskur",
    "işkur": "iskur",
    "diyanet": "diyanet",
    "tüik": "tuik",
    "tuik": "tuik",
    "tubitak": "tubitak",
    "tübitak": "tubitak",
    # Universities
    "odtu": "odtu",
    "odtü": "odtu",
    "metu": "odtu",
    "orta dogu teknik": "odtu",
    "itu": "itu",
    "istanbul teknik": "itu",
    "bogazici": "bogazici",
    "boğaziçi": "bogazici",
    "boun": "bogazici",
    "hacettepe": "hacettepe",
    "ankara universitesi": "ankarauni",
    "ankara üniversitesi": "ankarauni",
    "istanbul universitesi": "istanbuluni",
    "istanbul üniversitesi": "istanbuluni",
    "gazi universitesi": "gaziuni",
    "gazi üniversitesi": "gaziuni",
    "ege universitesi": "ege",
    "yildiz teknik": "yildiz",
    "yıldız teknik": "yildiz",
    "ytu": "yildiz",
    "marmara universitesi": "marmara",
    "bilkent": "bilkent",
    "koc universitesi": "kocuni",
    "koç üniversitesi": "kocuni",
    "sabanci": "sabanci",
    "sabancı": "sabanci",
    "anadolu universitesi": "anadoluuni",
    "anadolu üniversitesi": "anadoluuni",
    "acikogretim": "aof",
    "açıköğretim": "aof",
    "aof": "aof",
    "aöf": "aof",
    "dokuz eylul": "deu",
    "dokuz eylül": "deu",
    "karadeniz teknik": "ktu",
    "bahcesehir": "bau",
    "bahçeşehir": "bau",
    "yeditepe": "yeditepe",
    "ozyegin": "ozyegin",
    "özyeğin": "ozyegin",
    "akdeniz universitesi": "akdeniz",
    "cukurova": "cukurova",
    "çukurova": "cukurova",
    "uludag": "uludag",
    "uludağ": "uludag",
    "bursa uludag": "uludag",
    "selcuk universitesi": "selcuk",
    "selçuk": "selcuk",
    "sakarya universitesi": "sakarya",
    "kocaeli universitesi": "kocaeli",
    "ataturk universitesi": "ataturkuni",
    "atatürk üniversitesi": "ataturkuni",
    "ondokuz mayis": "omu",
    "ondokuz mayıs": "omu",
    "cerrahpasa": "iuc",
    "cerrahpaşa": "iuc",
}
